# Generated by Django 5.2.9 on 2025-12-15 09:16

from django.db import migrations

dependencies = [
    ("cards", "0001_initial"),
]

class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
    ]
